Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Albino
// Data atual  : 06/04/2020
Var
// Seção de Declarações das variáveis 
   i, num: inteiro
   q: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para i de 1 ate 6 faca
   leia (num)
        se (num>0) entao
        q <- q+1
        fimse
   fimpara
   escreval ("quantidade de numeros positivos", q)

Fimalgoritmo