Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2020
Var
// Seção de Declarações das variáveis 
   N, i, R: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreval ("Digite um numero")
   leia (N)
   escreval ("Tabuada do", N)

   para i de 1 ate 10 faca
   R <-(i*N)
   escreval (N,"x",i,"=",R)
   fimpara
   
Fimalgoritmo