Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2020
Var
// Seção de Declarações das variáveis 
   i, num, quadrado : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para i de 1 ate 5 faca
        leia (num)
        quadrado <- num*num
        escreval (quadrado)
   fimpara
   

Fimalgoritmo