Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/03/2020
Var
// Seção de Declarações das variáveis 
   n1, t: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval ("Digite um número que deseja saber a terceira parte")
   leia (n1)
   
   t <- n1/3
   escreval ("o resultado e", t)

Fimalgoritmo